name: Build report
on:
  push:

jobs:
  build:
    name: Build test report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npx eslint src/**/*.js gulpfile.js
      - name: Build HTML report
        uses: vivaldi-va/testcafe-html-report@master
        with:
          json_report: test/example.json

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          target-folder: example2
